name = "RainMaker"
uuid = "ce1e5628-4095-449b-8858-623a1e420393"
authors = ["Milan Kl√∂wer <milankloewer@gmx.de> and contributors"]
version = "0.1.0-DEV"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
SpeedyWeather = "9e226e20-d153-4fed-8a5b-493def4f21a9"

[compat]
CairoMakie = "0.12"
DocStringExtensions = "0.9"
SpeedyWeather = "0.10"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
