name = "RainMaker"
uuid = "ce1e5628-4095-449b-8858-623a1e420393"
authors = ["Milan Kl√∂wer <milankloewer@gmx.de> and contributors"]
version = "0.1.0-DEV"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
SpeedyWeather = "9e226e20-d153-4fed-8a5b-493def4f21a9"

[compat]
SpeedyWeather = "0.10"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
